blank_issues_enabled: false
contact_links:
  - name: Advice and general questions
    url: https://stackoverflow.com/questions/tagged/ARCore
    about: For advice and general questions, please use the ARCore tag on Stack Overflow.
  - name: ARCore SDK for Unity
    url: https://github.com/google-ar/arcore-unity-sdk/issues
    about: If using Unity, please use the https://github.com/google-ar/arcore-unity-sdk/issues issue tracker instead.

  - name: Developer documentation (Java)
    url: https://developers.google.com/ar/develop/java/
    about: Check out the developer documentation in case your question has already been answered.
  - name: API reference documentation (Java)
    url: https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/package-summary
    about: For API questions, refer to the API reference documentation.

  - name: Developer documentation (NDK)
    url: https://developers.google.com/ar/develop/c/
    about: Check out the developer documentation in case your question has already been answered.
  - name: API reference documentation (NDK)
    url: https://developers.google.com/ar/reference/c/
    about: For API questions, refer to the API reference documentation.

[8/21, 10:31 AM] Contact +63327231534: Private Personal Data mode security alerts & Manage security alerts Privacy & Safety nobody can use Hack link permanently closed block report banned terminated
[8/21, 10:33 AM] Contact +63327231534: Private Personal ⭐ Data mode security alerts & Manage security alerts Privacy & Safety nobody can use Hack link permanently closed block report banned terminated
[8/21, 10:34 AM] Contact +63327231534: Private Personal ⭐CyberGhost VPN
https://www.cyberghostvpn.com
Protect Your Online Privacy - Secure, Private, Reliable nobody can use Hack link permanently closed block report banned terminated
[8/21, 12:54 PM] adiksilingan: Private Personal ⭐Kaspersky™
https://www.kaspersky.com
Kaspersky™ Antivirus | Special Offer - Up To 42% Off, nobody can use hack link permanently closed block report banned terminated